"""The phason-defect Lagrangian — pinning what structure pins, no more.

The exponent attempt (phason_coupling_derivation) left k = c·(d_⊥ − τ) bracketed
because THREE things were undetermined: the energy convention c, the protection
count τ, and (implicitly) any defect-core contribution. Writing the actual
Lagrangian is the way to remove ambiguities that are fixed by structure rather
than by choice. This module does that and reports honestly which survive.

THE LAGRANGIAN (standard quasicrystal hydrodynamics + BPR substrate coupling)
-----------------------------------------------------------------------------
Fields: u(x) ∈ E∥ (phonon, physical slice), w(x) ∈ E⊥ (phason, internal).
Lifshitz / Lubensky–Ramaswamy–Toner quasicrystal elasticity (PRL 1985; de
Boissieu rev. 2008), with BPR's discrete-substrate-generated coupling D:

    F = ∫ d³x [ ½ C (∂u)²  +  ½ K (∂w)²  +  D (∂u)(∂w) ]            (1)

Dynamics: phonons propagate ( ½ρ(∂_t u)² ); phasons are DIFFUSIVE/overdamped
( Γ ∂_t w = −δF/δw ) — phasons carry no wave kinetic term. This asymmetry
matters below.

Defect: a phason dislocation, a line in physical 3-space whose Burgers vector
lives in E⊥:   ∮_γ dw = b_⊥ ,   |b_⊥| ~ one internal lattice unit, core size a.
Its strain field is ∂w ~ b_⊥ / r (2D dislocation form).

Substrate origin of D: in a periodic crystal D ≡ 0 by symmetry. In the BPR
quasicrystal D is generated by the discrete Z_p substrate — its natural size is
set by how strongly an internal mode projects onto the physical slice, i.e. by
the substrate's fundamental small parameter 1/p (one phase value out of p).

WHAT (1) PINS — and what it leaves open
---------------------------------------
(A) Energy convention c — PINNED to 2. F is QUADRATIC in the strains, so the
    energy a defect couples out of the reservoir scales as |amplitude|². There
    is no linear-in-amplitude energy in a quadratic free energy. c = 2 is fixed
    by the Lagrangian, not chosen.

(B) Protection count τ — PINNED to 1. The dislocation's winding is along ONE
    internal direction (its Burgers vector b_⊥). That direction is topologically
    rigid (∮dw = b_⊥ is quantized and unsuppressed). The OTHER d_⊥ − 1 internal
    directions are transverse to the winding and must be bridged by the projection
    coupling D, each costing 1/p. So the protected count is exactly τ = 1.

    ⇒ BULK exponent k_bulk = c·(d_⊥ − τ) = 2(d_⊥ − 1).  For 9-fold: k_bulk = 6.

(C) Defect-core contribution — NOT pinned. The singular core (a single substrate
    line, O(1) sites) couples to the reservoir through one fundamental Z_p domain.
    Its contribution is a NEW coupling g_core that (1) introduces but does not
    determine. Three scalings are physically defensible:
        g_core ~ O(1)   → k = k_bulk      = 6   (lifts robustly)
        g_core ~ 1/p    → k = k_bulk + 1  = 7   (marginal — matches k_req)
        g_core ~ 1/p²   → k = k_bulk + 2  = 8   (does not lift)
    The MIDDLE one (single-site core ⇒ one factor 1/p ⇒ k = 7) is the natural
    reading and reproduces the required exponent — but g_core ~ 1/p is a
    HYPOTHESIS about the core, not a theorem from (1).

HONEST STATUS
-------------
Writing the Lagrangian collapses the old 4-corner bracket {3,4,6,8} to a single
line k = 6 + (core power), fixing c and τ from real structure. It does NOT pin
the exponent by itself: the last unknown is the core coupling g_core, one number.
The natural single-site value gives 7; proving g_core ~ 1/p (rather than O(1) or
1/p²) requires a short-distance theory of the defect core that BPR does not yet
have. So: the Lagrangian is genuine progress (2 of 3 ambiguities pinned) and the
remaining gap is now a SINGLE, sharply-stated quantity rather than a 40-order
span. It is NOT a closed derivation of (1/p)^7.
"""
from __future__ import annotations

from dataclasses import dataclass

from .phason_sector import embedding_rank


# --- The terms of F, as structured data (for the doc + tests) --------------

@dataclass(frozen=True)
class LagrangianTerm:
    symbol: str
    name: str
    fixed_by_structure: bool
    note: str


FREE_ENERGY_TERMS = (
    LagrangianTerm("½C(∂u)²", "phonon elastic", True,
                   "quadratic in physical strain — the sector BPR already has"),
    LagrangianTerm("½K(∂w)²", "phason elastic", True,
                   "quadratic in internal strain; K ≈ 0.05 C (phasons softer)"),
    LagrangianTerm("D(∂u)(∂w)", "phonon–phason coupling", False,
                   "ZERO in a periodic crystal; in BPR generated by the Z_p "
                   "substrate, natural size ~1/p per bridged internal direction"),
)


def energy_convention_c() -> dict:
    """c is PINNED to 2: F is quadratic, so reservoir energy ~ |amplitude|²."""
    return {
        "c": 2,
        "pinned": True,
        "reason": "free energy F is quadratic in the strains; there is no "
                  "linear-in-amplitude energy term, so extracted energy ∝ |A|².",
    }


def protection_count_tau() -> dict:
    """τ is PINNED to 1: the dislocation winds along ONE internal direction."""
    return {
        "tau": 1,
        "pinned": True,
        "reason": "∮dw = b_⊥ is quantized along a single internal direction "
                  "(topologically rigid, unsuppressed); the other d_⊥−1 "
                  "transverse internal directions are bridged by D at cost 1/p each.",
    }


def bulk_exponent(n: int = 9) -> int:
    """k_bulk = c·(d_⊥ − τ) = 2(d_⊥ − 1), with c, τ pinned by the Lagrangian."""
    d_perp = embedding_rank(n) - 2
    c = energy_convention_c()["c"]
    tau = protection_count_tau()["tau"]
    return c * (d_perp - tau)


@dataclass(frozen=True)
class CoreScenario:
    g_core_scaling: str
    extra_power: int
    total_k: int
    verdict: str
    natural: bool


def core_scenarios(n: int = 9) -> list[CoreScenario]:
    """The three defensible core couplings and the total exponent each gives.
    Only g_core ~ 1/p is flagged 'natural' (single-site core), and even that is
    a HYPOTHESIS — not pinned by the quadratic Lagrangian."""
    kb = bulk_exponent(n)
    return [
        CoreScenario("g_core ~ O(1)", 0, kb + 0,
                     "lifts robustly (ε far above threshold)", False),
        CoreScenario("g_core ~ 1/p", 1, kb + 1,
                     "marginal — reproduces k_req ≈ 7 (single-site core)", True),
        CoreScenario("g_core ~ 1/p²", 2, kb + 2,
                     "does not lift (ε below threshold)", False),
    ]


def lagrangian_pins(n: int = 9) -> dict:
    """Summary of what the Lagrangian fixes vs leaves open."""
    c = energy_convention_c()
    tau = protection_count_tau()
    kb = bulk_exponent(n)
    natural = [s for s in core_scenarios(n) if s.natural][0]
    return {
        "n_fold": n,
        "c_pinned": c["pinned"],
        "tau_pinned": tau["pinned"],
        "k_bulk": kb,
        "core_pinned": False,                # the one remaining unknown
        "natural_total_k": natural.total_k,  # 7 for 9-fold, but a hypothesis
        "fully_derived": False,
        "remaining_unknown": "g_core (defect-core substrate coupling): one number; "
                             "single-site reading gives 1/p ⇒ k=7, unproven.",
    }


def report(n: int = 9) -> str:
    p = lagrangian_pins(n)
    lines = [
        "Phason-defect Lagrangian — what it pins",
        "=======================================",
        "F = ∫ [ ½C(∂u)² + ½K(∂w)² + D(∂u)(∂w) ] d³x   (LRT quasicrystal elasticity)",
        "defect: phason dislocation ∮dw = b_⊥ ;  D generated by Z_p substrate ~1/p",
        "",
        f"(A) energy convention  c   = 2   PINNED  (F quadratic ⇒ energy ∝ |A|²)",
        f"(B) protection count   τ   = 1   PINNED  (single winding direction)",
        f"    ⇒ bulk exponent    k_bulk = 2(d_⊥−1) = {p['k_bulk']}  (9-fold, d_⊥=4)",
        "",
        "(C) defect-core coupling g_core — NOT pinned:",
    ]
    for s in core_scenarios(n):
        flag = "  <- natural (hypothesis)" if s.natural else ""
        lines.append(f"      {s.g_core_scaling:<14} ⇒ k={s.total_k}  {s.verdict}{flag}")
    lines += [
        "",
        f"STATUS: 2 of 3 ambiguities pinned; total k = {p['k_bulk']} + (core power).",
        f"Natural single-site core ⇒ k = {p['natural_total_k']} (matches k_req≈7),",
        "but g_core ~ 1/p is a HYPOTHESIS, not a theorem. The Lagrangian reduces",
        "the gap to ONE number (the core coupling); it does not close it. A clean",
        "(1/p)^7 still requires a short-distance defect-core theory BPR lacks.",
    ]
    return "\n".join(lines)


if __name__ == "__main__":  # pragma: no cover
    print(report())
