name: bpr-minimal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21
  - scipy>=1.7
  - matplotlib>=3.5
  - sympy>=1.9
  - jupyter
  - jupyterlab
  - pytest>=6.0
  - pytest-cov
  - black
  - isort
  - flake8
  - pre-commit
  - pandas
  - h5py
  - pip
  # NO FEniCS - for systems where FEniCS installation fails
  # Most functionality still works, some tests will be skipped